INSERT INTO USER (USER_ID, EMAIL, KAKAO_ID, NICKNAME, PROFILE_IMG, REFRESH_TOKEN)
VALUES (2, 'test@test.com', '12341234', '친구2', 'ico_Bear', 'fadlskjf');
INSERT INTO USER (USER_ID, EMAIL, KAKAO_ID, NICKNAME, PROFILE_IMG, REFRESH_TOKEN)
VALUES (3, 'test1@test.com', '1111111', '친구3', 'ico_Bear', 'adsfasd');
INSERT INTO USER (USER_ID, EMAIL, KAKAO_ID, NICKNAME, PROFILE_IMG, REFRESH_TOKEN)
VALUES (4, 'test2@test.com', '222222', '친구4', 'ico_Bear', 'afdsdf');
INSERT INTO USER (USER_ID, EMAIL, KAKAO_ID, NICKNAME, PROFILE_IMG, REFRESH_TOKEN)
VALUES (1, 'test3@test.com', '3333333', '친구5', 'ico_Bear', 'afsdfdgggsdg');

INSERT INTO TRIP (TRIP_ID, END, END_DATE, INVITE_CODE, OWNER_ID, START_DATE, TRIP_NAME)
VALUES (1, false, '2021-06-03', 11, 1, '2021-05-25', '테스트 여행');

INSERT INTO EXPENSE (INDIVIDUAL, PAY_DATE, PAYER_ID, TITLE, TOTAL_PRICE, TRIP_ID)
VALUES (false, '2021-05-19', 5, '햄버거 테스트', 20000, 1);
INSERT INTO EXPENSE (INDIVIDUAL, PAY_DATE, PAYER_ID, TITLE, TOTAL_PRICE, TRIP_ID)
VALUES (false, '2021-05-20', 1, '치킨 테스트',25000 , 1);
INSERT INTO EXPENSE_DETAIL (EXPENSE_ID, PRICE, USER_ID)
VALUES (1, 15000, 1);
INSERT INTO EXPENSE_DETAIL (EXPENSE_ID, PRICE, USER_ID)
VALUES (1, 5000, 2);
INSERT INTO EXPENSE_DETAIL (EXPENSE_ID, PRICE, USER_ID)
VALUES (2, 5000, 5);
INSERT INTO EXPENSE_DETAIL (EXPENSE_ID, PRICE, USER_ID)
VALUES (2, 15000, 1);
INSERT INTO EXPENSE_DETAIL (EXPENSE_ID, PRICE, USER_ID)
VALUES (2, 5000, 3);