INSERT INTO USER (USER_ID, EMAIL, KAKAO_ID, NICKNAME, PROFILE_IMG, REFRESH_TOKEN) VALUES (2,'test@test.com', '12341234','친구2','ico_Bear','fadlskjf');
INSERT INTO USER (USER_ID, EMAIL, KAKAO_ID, NICKNAME, PROFILE_IMG, REFRESH_TOKEN) VALUES (3,'test1@test.com', '1111111','친구3','ico_Bear','adsfasd');
INSERT INTO USER (USER_ID, EMAIL, KAKAO_ID, NICKNAME, PROFILE_IMG, REFRESH_TOKEN) VALUES (4,'test2@test.com', '222222','친구4','ico_Bear','afdsdf');
INSERT INTO USER (USER_ID, EMAIL, KAKAO_ID, NICKNAME, PROFILE_IMG, REFRESH_TOKEN) VALUES (5,'test3@test.com', '3333333','친구5','ico_Bear','afsdfdgggsdg');